kind: Deployment
apiVersion: apps/v1
metadata:
  name: app1
  labels:
    app: app1
    purpose: ingress

spec:
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      app: app1
      purpose: ingress
  # This is pod definition
  template:
    metadata:
      labels:
        app: app1
        purpose: ingress
    spec:
      containers:
      - name: app1
        image: saikumar718/app1:1.0
---
apiVersion: v1 
kind: Service 
metadata:
  name: app1
spec:
  selector:
    app: app1
    purpose: ingress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: app1
      annotations:
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/group.name: saikumar
        alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
        alb.ingress.kubernetes.io/scheme: internet-facing
    spec:
      ingressClassName: alb
      rules:
      - host: "app1.devopswithaws.store"
        http:
          paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: app1
                port:
                  number: 80
