kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    app: app1
spec:
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      app: app1
      purpose: ingress
  # This is pod definition
  template:
    metadata:
      labels:
        app: app1
        purpose: ingress
    spec:
      containers:
      - name: app1
        image: saikumar718/app1:v1.0
---
apiVersion: v1 
kind: Service 
metadata:
  name: nginx
spec:
  selector:
    app: app1
    purpose: ingress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
